name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  create: # create branch or tag
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build packages
        run: |
          make TRACK=stable
          make TRACK=unstable
