name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  create: # create branch or tag
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build packages
        run: |
          make TRACK=stable
          make TRACK=unstable
      - name: Generate package feeds
        run: |
          make TRACK=stable update
          make TRACK=unstable update
